Lights fixes
robherring/generic_device pull request #4
Opened 2017-06-06 15:59 UTC by aleksander0m

The following patches make the android brightness settings work properly.

2017-06-06 16:04 UTC, aleksander0m commented
The first patch isn't generic enough probably, now that I see it, as it fixes the sysfs path to the "pic-backlight" directory...

2017-06-07 19:44 UTC, robherring requested changes
patches 2 and 4 look good.

2017-06-07 19:44 UTC, robherring commented on ueventd.rc
> -/sys/class/backlight*		 max_brightness 0664 system system
It's preferred to set file permissions in ueventd.rc. If the max_brightness line isn't needed, can't we just delete that one line?

My intention is to move all of these to system/core

2017-06-07 19:44 UTC, robherring commented on lights/lights.c
> +		ALOGE("invalid max brightness: %ld\n", brightness_max);
Can this really happen with a mainline kernel?

2017-06-07 19:59 UTC, aleksander0m commented on ueventd.rc
> -/sys/class/backlight*		 max_brightness 0664 system system
Aren't ueventd.rc rules applied *only* for device files exposed via uevents? From some tests with real HW that is what it looked like, and those /sys/class/backlight/*/brightness files were not getting the correct permissions set. In particular, brightness wasn't being set RW.

2017-06-07 20:00 UTC, aleksander0m commented on lights/lights.c
> +		ALOGE("invalid max brightness: %ld\n", brightness_max);
It can if e.g. there's a permission error when trying to read from the brightness file (the reader function returns -errno).

2017-07-10 14:03 UTC, robertfoss commented
@aleksander0m Is this PR still in progress?

2017-07-10 17:32 UTC, aleksander0m commented
@robertfoss @robherring It is in progress, but I didn't spend much more time on this yet.

The two outstanding issues are the ueventd.rc vs init logic to change permissions, and the 'generic' filename used for brightness control (i.e. not always "pic-backlight").

Regarding the first issue, and as far as I understand, setting permissions on ueventd.rc only applies when there's some device file being notified via uevents; if there is none, as in this case with the lights control, the ueventd.rc permissions don't apply (they will never run), and we need the file permissions changed via init rules. But really I'm not that experienced to say this is always the case, especially since the kernel I used for testing where I validated those assumptions is the upstream Linux kernel and not an android-ized one.

2017-07-14 15:53 UTC, aleksander0m commented
@robherring I have now updated this branch, removing the commit that moved the chmod to init.rc, and adding a new one which just removes the ueventd.rc line that changes the max_brightness file permissions. I still left the log updated for when read_int() fails, feel free to leave that out of the merge if you think it really isn't that useful.

2017-07-14 16:03 UTC, merged